# Generated by Django 5.0.7 on 2024-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipy_name', models.CharField(max_length=100)),
                ('recipy_description', models.TextField()),
                ('recipy_image', models.ImageField(upload_to='recipy')),
            ],
        ),
    ]
